language: python
cache: false
python:
    - '3.11'
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=3.11-django4.2
    - TOXENV=flake8
    - TOXENV=cov
install: pip install -U tox
script: tox -v -- -v
after_success:
  - .tox/$TOXENV/bin/coverage xml
  - .tox/$TOXENV/bin/codecov -e TOXENV
