[tox]
envlist =
    py311-django42
    flake8

[testenv]
deps =
    -r{toxinidir}/requirements/default.txt
    -r{toxinidir}/requirements/test.txt
    django42: -r{toxinidir}/requirements/test-django42.txt
commands =
    pytest --cov-report=xml {posargs}

[testenv:flake8]
deps = flake8
commands = flake8 deux

[flake8]
max-line-length = 100
exclude = docs
